# Generated by Django 5.2 on 2025-04-15 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0017_voiceinteraction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoiceInteraction',
        ),
    ]
