# Generated by Django 5.2 on 2025-04-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0018_remove_userprofile_activity_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('zh-hans', 'Chinese'), ('ar', 'Arabic'), ('hi', 'Hindi')], default='en', max_length=10, null=True),
        ),
    ]
